import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

// GET user's saved bikes (My Garage)
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const phone = searchParams.get("phone");

    if (!phone) {
      return NextResponse.json(
        { success: false, error: "Phone number required" },
        { status: 400 }
      );
    }

    const user = await prisma.user.findUnique({
      where: { phone },
      include: {
        garageBikes: {
          include: {
            bikeModel: true,
          },
        },
      },
    });

    if (!user) {
      return NextResponse.json({ success: true, data: [] });
    }

    return NextResponse.json({ success: true, data: user.garageBikes });
  } catch (error) {
    console.error("Error fetching My Garage:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch garage bikes" },
      { status: 500 }
    );
  }
}

// POST add bike to My Garage
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { phone, bikeModelId, nickname, isPrimary = false } = body;

    if (!phone || !bikeModelId) {
      return NextResponse.json(
        { success: false, error: "Phone and bikeModelId are required" },
        { status: 400 }
      );
    }

    let user = await prisma.user.findUnique({ where: { phone } });
    if (!user) {
      user = await prisma.user.create({
        data: {
          phone,
          passwordHash: "$2a$10$autogeneratedhash",
        },
      });
    }

    // If making primary, unmark other garage bikes
    if (isPrimary) {
      await prisma.userBike.updateMany({
        where: { userId: user.id },
        data: { isPrimary: false },
      });
    }

    const userBike = await prisma.userBike.upsert({
      where: {
        userId_bikeModelId: {
          userId: user.id,
          bikeModelId,
        },
      },
      update: {
        nickname: nickname || undefined,
        isPrimary,
      },
      create: {
        userId: user.id,
        bikeModelId,
        nickname,
        isPrimary,
      },
      include: {
        bikeModel: true,
      },
    });

    return NextResponse.json({ success: true, data: userBike });
  } catch (error) {
    console.error("Error updating My Garage:", error);
    return NextResponse.json(
      { success: false, error: "Failed to save bike to garage" },
      { status: 500 }
    );
  }
}
